micronaut:
    application:
        name: demo
    server:
      port: 8081

mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/Servicing

router:
  static-resources:
    swagger:
      paths: classpath:META-INF/swagger
      mapping: /swagger/**


github:
  organization: micronaut-projects
  repo: micronaut-core
#end::githubconfig[]